language: node_js

node_js:
  - 10.15.1
dist: docs
addons:
  chrome: stable
before_script:
  - yarn
after_script:
  - harp server docs


deploy:
  provider: heroku
  api_key:
    secure: '7f89b8f6-b0e7-40ea-bc01-d8ae1a408fce'
  run: "harp server docs --port $PORT"