language: node_js

node_js:
  - 10.15.1
dist: docs
addons:
  chrome: stable
script: true
after_script:
  - harp server docs

deploy:
  provider: heroku
  api_key:
    secure: {{HEROKUAPI}}
  run: "harp server docs --port $PORT"