language: node_js

node_js:
  - 10.15.1
dist: docs
script: 'true'
addons:
  chrome: stable
before_script:
  - yarn
after_script:
  - harp server docs


deploy:
  provider: heroku
  api_key:
    secure: process.env.HEROKUAPI
  run: "harp server docs --port $PORT"